# Generated by Django 5.2.8 on 2025-11-17 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_studentcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourses',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='courses.course'),
        ),
    ]
