# Generated by Django 5.2.8 on 2025-11-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_studentcourses_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourses',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
